version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: docker_testing
    container_name: docker_testing
    ports:
      - "80:80"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - ./log:/rails/log
      - ./tmp:/rails/tmp
      - ./storage:/rails/storage
    depends_on:
      - db
    command: ["./bin/thrust", "./bin/rails", "server"]

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_production
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: